#!/usr/bin/env python
# -*- coding:utf-8 -*-
import os
from biplist import *



def get_name(Dir):
    with open('Result.txt', 'a') as f:          # w:新建（文件不存在，新建） a：打开 r：可读可写（文件不存在报错）
        for dirpath, dirnames, filenames in os.walk(Dir):   # os.walk   #遍历路径下的文件及文件夹
            for filename in filenames:
                if filename == '.com.apple.mobile_container_manager.metadata.plist':
                    try:
                        dir = os.path.join(dirpath, filename)  #获取该plist所在的路径
                        p = readPlist(dir)
                        pgk_name = p['MCMMetadataIdentifier']
                        result = {dirpath: pgk_name}
                        f.write(str(result))
                        f.write("\n")
                    except BaseException as e:
                        print(e)


# l1 = os.path.abspath(__file__).split('\\', -1)  # 获取当前exe所在路径并转为list 
